### ISSUE TITLE
Problem with injection

### ISSUE THREAD

**Issue by Withors** [radioegor146/jar-to-dll#19]
[11May2024 13:24:04.407] [Thread-7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1069]: java.lang.NoClassDefFoundError: ForgeInjector
[11May2024 13:24:04.407] [Thread-7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: Caused by: java.lang.ClassNotFoundException: ForgeInjector
[11May2024 13:24:04.407] [Thread-7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
[11May2024 13:24:04.407] [Thread-7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
[11May2024 13:24:04.407] [Thread-7/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1078]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)

**Comment by 0xuint** [comment]
такая-же проблема, ты смог решить?

**Comment by Withors** [comment]
неть

**Comment by radioegor146** [comment]
Версия MC?

**Comment by Withors** [comment]
1.16.5 forge

**Comment by Zundonza** [comment]
Была такая же проблема. Скомпилировал мод на восьмой джаве + запустил jar to dll на восьмой. Заинжектить получилось, мод работает. Но сообщение об ошибке с ForgeInjector всё равно никуда не делось
