### ISSUE TITLE
 вопрос 

### ISSUE THREAD

**Issue by whycantiusemyname** [radioegor146/jar-to-dll#7]
Я использую команду readme. MD в команде, а потом я получаю dll, но я не могу ввести его внутрь.
Иногда появляется "class no found" 
 Показывать успех 
 но не все 
 Я не буду им пользоваться?

**Comment by radioegor146** [comment]
Hi. It'll be better if you'll reask the question in English (since GitHub is a multilingual and international platform). Also describing your error more detailed will help me resolve it.

**Comment by GruverMakingBad** [comment]
Starting!
Thread: Thread-7 [net.minecraft.launchwrapper.LaunchClassLoader]
Loading 4 classes
4 loaded successfully
Instancing com.sun.proxy.Main
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
	at com.sun.proxy.Main.<init>(Main.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at loader.MagicTheInjecting.run(MagicTheInjecting.java:109)
	Как пофиксить это? Подскажи плиз.
